# Generated by Django 3.1.5 on 2021-04-13 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
        ('crops', '0002_crop_ave_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCropFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('crop_fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.cropfruit')),
                ('crop_growth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.cropgrowth')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCropState',
            fields=[
                ('usercropfavorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='associates.usercropfavorite')),
                ('state', models.CharField(choices=[('Seed', 'Seed'), ('Planting', 'Planting'), ('Harvesting', 'Harvesting'), ('Withered', 'Withered')], max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('associates.usercropfavorite',),
        ),
        migrations.CreateModel(
            name='UserWeatherHistory',
            fields=[
                ('weatherhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather.weatherhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('weather.weatherhistory',),
        ),
        migrations.CreateModel(
            name='UserWeatherForcast',
            fields=[
                ('weatherforcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather.weatherforcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('weather.weatherforcast',),
        ),
    ]
