# Generated by Django 3.1.5 on 2021-04-13 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('bulk_soil_density', models.FloatField(default=0)),
                ('surface_pressure', models.FloatField(default=0)),
                ('minimum_temperature', models.FloatField(default=0)),
                ('maximum_temperature', models.FloatField(default=0)),
                ('precipitation', models.IntegerField(default=0)),
                ('atmospheric_humidity', models.FloatField(default=0)),
                ('evapotranspiration', models.FloatField(default=0)),
                ('soil_mositure_0_10', models.FloatField(default=0)),
                ('soil_mositure_10_40', models.FloatField(default=0)),
                ('soil_mositure_40_100', models.FloatField(default=0)),
                ('soil_mositure_100_200', models.FloatField(default=0)),
                ('soil_temp_0_10', models.FloatField(default=0)),
                ('soil_temp_10_40', models.FloatField(default=0)),
                ('soil_temp_40_100', models.FloatField(default=0)),
                ('soil_temp_100_200', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherForcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('minimum_temperature', models.FloatField(default=0)),
                ('maximum_temperature', models.FloatField(default=0)),
                ('ave_temperature', models.FloatField(default=0)),
                ('atmospheric_humidity', models.FloatField(default=0)),
                ('precipitation', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
